// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaccigbkopobihlhhgpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphY2NpZ2Jrb3BvYmlobGhoZ3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTM1OTksImV4cCI6MjA2MjU2OTU5OX0.H318e7xY2vkZdqsOSGtqHoCh4ExJl33aR5y0qzHExtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);